### ISSUE TITLE
Set default filter on which file to extract for Edge (Chromium) and Opera

### ISSUE THREAD

**Issue by dannejosefsson** [webdriverextensions/webdriverextensions-maven-plugin-repository#76]
As described in https://github.com/webdriverextensions/webdriverextensions-maven-plugin/issues/50, the extract driver command breaks for Edge (Chromium). This seems also to be the issue with Opera and some further hints about that is that the Opera drivers are commented out, like at [InstallDriversOnMac32BitMachineMojoTest.java#L82-L83](https://github.com/webdriverextensions/webdriverextensions-maven-plugin/blob/1f26b75c6db0a4feb81214e4d109dcf39379079a/src/test/java/com/github/webdriverextensions/InstallDriversOnMac32BitMachineMojoTest.java#L82-L83).

**Comment by sephiroth-j** [comment]
I am supporting this. Although webdriverextensions/webdriverextensions-maven-plugin#50 is fixed in the upcoming release v3.3.0, the installed driver for Opera and Edge will be located in subfolder (e.q. "edgedriver-windows-64bit") because of the other files and folders in their archives. This requires users to adjust the path and newer features like webdriverextensions/webdriverextensions-maven-plugin#26 will not work for these drivers.
